name: EpicRPG
version: 2.0.2-ALPHA
main: me.Vark123.EpicRPG.Main
author: Vark123
depend: [CalendarEvents,MythicMobs,NBTAPI,ProtocolLib,EpicOptions]
api-version: 1.18

libraries:
  - io.github.rysefoxx.inventory:RyseInventory-Plugin:1.6.5

commands:
  staty:
    aliases: [stats, statystyki]
  sprzedaj:
  chat:
  chatclear:
  kon:
    aliases: [horse]
  epicrpg:
    aliases: [erpg, rpg]
  sklep:
  drop:
  level:
    aliases: [lvl, poziom]
  stygia:
    aliases: [sg]
  endtut:
  kosz:
    aliases: [smietnik, bin]
  rpgmm:
  soulbindgive:
    aliases: [sbgive, sb]
  uniquegive:
    aliases: [ugive]
  stygiabuy:
    aliases: [sgbuy]
  coinsbuy:
    aliases: [dcbuy]
  dragoncoins:
    aliases: [coins]
  ruda:
    aliases: [brylkirudy]
  brbuy:
    aliases: [rudabuy, brylkirudybuy]
  coinscmd:
  rpgmenu:
  rotacja:
  kasa:
  reset:
  blackrock:
  bizuteria:
    aliases: [jewerly, akcesoria, biz, akc, jew]
  stygiamod:
    aliases: [sgmod]
  reputation:
    aliases: [rep,reputacja]
  reputationmod:
    aliases: [repmod]
  advancedbuy:
    aliases: [ab,abs,advancedbuysystem]
  event:
    aliases: [evc, ev]
  event2:
    aliases: [evc2, ev2]
  epicboost:
  modyfikatory:
    aliases: [modyfikator, mod, booster, boosters, boost, boosts]
  epicexp:
    aliases: [exp, eexp]
  ekwipunek:
    aliases: [eq]
  epicmoney: